[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "api_client"
version = "0.1.0"
description = "A highly customizable and easy-to-use API client built on top of httpx."
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT License" }
keywords = ["api", "client", "httpx", "pydantic", "development"]
authors = [
  {name = "Amit Afre", email = "your.email@example.com"}
]
maintainers = [
  {name = "Your Name", email = "your.email@example.com"}
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
  "httpx",
  "pydantic",
  "pydantic-settings",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-asyncio",
]

[project.urls]
"Homepage" = "https://github.com/aafre/APIClient"
"Bug Reports" = "https://github.com/aafre/APIClient/issues"
"Source" = "https://github.com/aafre/APIClient"

[tool.setuptools.packages.find]
where = ["api_client"]
exclude = ["tests*"]
